runtime: python37
# https://cloud.google.com/appengine/docs/standard
instance_class: F2
# scaling: see https://medium.com/google-cloud/app-engine-scheduler-settings-and-instance-count-4d1e669f33d5
automatic_scaling:
  # min_instances: 1
  max_instances: 1
  # max_concurrent_requests: 80 # standard: 10, max: 80
  # max_pending_latency: 8s
  # min_pending_latency: 6s
handlers:
- url: /.well-known
  static_dir: typeworldserver/static
- url: /static
  static_dir: typeworldserver/static
- url: /.*
  secure: always
  script: auto
entrypoint: gunicorn -t 0 -b :$PORT -w 2 typeworldserver:app
